#!/usr/bin/perl -w


my $file = "Apply_OffLine";

my $mtime = (stat $file)[9];

my @time = localtime($mtime);
print "mtime is {$mtime}\n";
my $year= 1999 + $time[5];
my $lt = sprintf "%4d-%2.2d-%2.2dT%2.2d:%2.2d", $year, $time[4], $time[3], $time[2], $time[1];
print "localtime $year  $lt\n";
my $TZ = $time[8] ? "PDT" : "PST";
print "is dst {$time[8]} $TZ \n";

