#!/usr/local/bin/perl -wT


$ENV{PATH} = "/bin:/usr/bin";


#use lib '/www/jobs/lib/';
#use Job_Appl_Info3;
use strict;


my @file = ( 'c:\some bogus window\file');


foreach my $f ( @file )
{
   print "Before:: $f \n";
   $f =  unTaint ($f);
   print "After:: $f \n";
}


sub unTaint
{
 
   my $in = shift;
   my $nl = "";
   $in =~ s/^\s*//;				#remove leading whitespace...
   $in =~ s/\s+/_/g;
   $in =~ s/[;:]/_/g;
   $in =~ s[\\][_]g;
#   print "unTaint'ing $in $nl";
   if ($in =~/^([-\@\w\d_\/][-\@\w\d_.\/]*)$/)  #1st char can letter, 
                                                #number, minus or at
   {                                            #other characters can be dot & slash
       $in = $1;
   } else
   {
       print " dying in unTaint with >$in<$nl";
       die "Variable $in is tainted\n";
   }
   return $in;
} 
