#!/usr/local/bin/perl -wT

# save the entered info to a file & redisplay
# this script is intended to management info that is editable by 
# the course intructors:  course.cgi is a more general tool

$ENV{PATH} = "/bin:/usr/bin";

use Date::Calc qw { Today Delta_Days Add_Delta_Days};
use lib '/www/jobs/lib/';
use lib '/var/www/lib/perl/sql_lib';
use newPAsql_Sessions;
use Debug;
use strict;
use CGI;
use CGI::Carp 'fatalsToBrowser'; 
my $q = new CGI;
Debug::Set_Debug(10);
my $this_script = "/cgi-bin/Jobs/xtest";


print $q->header(-type=> "text/html", -expires=>'now'), "\n";
print $q->start_html( -title  => "PandA Online Job Appl Admin ", 
                      -style  =>{'src'=>'/jobs/lib/job.css'},),"\n";
my $user = newPAsql_Sessions::getPHASuser();

#print "user is {$user}\n";

#print $q->redirect("https://secure.phas.ubc.ca/gve_login.php?req_url=$this_script")    unless $user;  

print qq{" this is xtest ... user is {$user} ..."};
	    
print $q->end_html;
exit;





