#!/usr/local/bin/perl -wT

# save the entered info to a file & redisplay
# this script is intended to management info that is editable by 
# the course intructors:  course.cgi is a more general tool

$ENV{PATH} = "/bin:/usr/bin";

use Date::Calc qw { Today Delta_Days Add_Delta_Days};
use lib '/www/jobs/lib/';

use Job_Ad_MetaData;
use Job_Appl_Info3;
use strict;
use CGI;
use CGI::Carp 'fatalsToBrowser';

my $this_script = "/cgi-bin//Jobs/xtest2";

my $title = "P &amp; A Job Form";
my $title2 = " ";
my $New = 0;	
my $version = "0.2.2";
my $tdtopright = '<td valign="top" align="right">';
my $tdtop      = '<td valign="top">';
my $sp = '&nbsp;';


my $q = new CGI;

print $q->header(-type=> "text/html", -expires=>'now'), "\n";
print $q->start_html( -title   => "PandA Online Job Applocation Info ", 
                      -bgcolor => "white",
                      -style=>{'src'=>'/jobs/lib2/job.css'},
                    ),"\n";

print qq{" this is xtest2 ... no reference to sessions ..."};
	    
print $q->end_html;
exit;







sub dump_it
{
	print "<h2> Dump of the query </h2><br />\n";
        print $q->Dump;
        print "<hr />";
}


